### PR TITLE
Code style fixes

### PR DESCRIPTION
**Pull request by stokito**
There was a lot of minor style issues.
I automatically reformatted the usteer.js in IntelliJ IDE. You can try a trial version of the IDE. Open source VS code, Eclipse also have automatic reformatting.

Please check the commit 54893b5a4690138c808d8c7a4e4422a130903b1c

The poolData doesn't exists. Maybe that's some method? Then you should call it like `pollData()`.
You can add me as a contributor to your repo so I can commit such fixes directly.

### CODE REVIEW

**Comment by Ramon00** [comment]
> There was a lot of minor style issues. I automatically reformatted the usteer.js in IntelliJ IDE. You can try a trial version of the IDE. Open source VS code, Eclipse also have automatic reformatting.
> 

Guess im oldschool. I just use a text editor :-) 

But thx for the style update. One question though, why name it to `vlanInfos`, it is not really vlans, I guess wlans would be a better description. 


> Please check the commit [54893b5](https://github.com/Ramon00/luci/commit/54893b5a4690138c808d8c7a4e4422a130903b1c)
> 
> The poolData doesn't exists. Maybe that's some method? Then you should call it like `pollData()`. You can add me as a contributor to your repo so I can commit such fixes directly.

Ah the polldata should not be there (yet). I was busy adding refresh, but that part is not finished yet.

**Comment by stokito** [comment]
Ok, please merge and rename as you wish. The main change is that we have extracted function to avoid code duplication

5 декабря 2023 г. 22:51:04 GMT+02:00, Ramon Van Gorkom ***@***.***> пишет:

**Comment by Ramon00** [comment]
ok thx. Will do

**Comment by Ramon00** [comment]
@stokito Im getting a `Unexpected token ']'` after merging. Can you spot it where it is?

**Comment by stokito** [comment]
> @stokito Im getting a `Unexpected token ']'` after merging. Can you spot it where it is?

Sorry, I just got to bed. But I beleieve that's from the last commit where you have table headers with translations. There you had `_('name', 'description')` and changed to _('name'), _('description')`.
You need to check that part

**Pull request merged**
